name: Build

on: [push, pull_request]

jobs:
  build-and-test-mr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - name: 'Setup: Java 8 env'
        run: echo "JAVA8_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: 'Setup: Java 11 env'
        run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: 'Setup: Java 17 env'
        run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew opensearch-hadoop-mr:build